[workspace]
authors = ["zaynram <ramdasszayn@gmail.com>"]
channels = ["conda-forge"]
name = "medlink"
platforms = ["win-64"]
version = "0.1.0"
preview = ["pixi-build"]

[environments]
default = ['gui', 'dev']
dev = ['dev']

[tasks]
start = "python main.py"

[dependencies]
python = ">=3.12,<3.14"


[feature.dev.dependencies]
ipywidgets = ">=8.1.7,<9"
ipykernel = ">=6.30.1,<7"
pyinstaller = ">=6.15.0,<7"

[feature.gui.pypi-dependencies]
tqdm = "*"
wxpython = "*"
gooey = "*"

[pypi-dependencies]
pymupdf = ">=1.26.4, <2"
ollama = ">=0.5.3, <0.6"
pydantic = "==2.12.0a1"
