[workspace]
authors = ["zaynram <ramdasszayn@gmail.com>"]
channels = ["conda-forge"]
name = "medical-record-analysis"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.14"
ipywidgets = ">=8.1.7,<9"
ipykernel = ">=6.30.1,<7"
mypy = ">=1.17.1,<2"
wxpython = ">=4.2.3,<5"

[pypi-options]

[pypi-dependencies]
tqdm = "*"
pymupdf = ">=1.26.4, <2"
ollama = ">=0.5.3, <0.6"
gooey = ">=1.0.8.1, <2"
