"""
Generate a Family Trust document from a TrustData instance.

Preserves the exact 12-article + 4-schedule structure from the original
build.py, but consumes typed Pydantic models instead of a raw dict.
All bugs from the original (boolean conditionals, KeyError crashes) are
fixed by virtue of typed attribute access.
"""

from __future__ import annotations

import logging
from functools import cached_property
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from trust_generator.v2.config import AppConfig, load_config
from trust_generator.v2.generators.docx_formatter import DocxFormatter
from trust_generator.v2.schema import (
    BeneficiaryDeath,
    DisputeResolution,
    DistributionStandard,
    PowerOfAppointment,
    PropertyClassification,
    RemoteContingent,
    RetirementStrategy,
    SurvivingAmendment,
    TangibleDistribution,
    TrustData,
    TrusteeCompensation,
    TrustType,
)

log = logging.getLogger(__name__)

try:
    __version__ = version("trust-generator")
except PackageNotFoundError:
    __version__ = "2.2.0-dev"


def generate_trust_document(
    data: TrustData,
    output_path: str | Path,
    config: AppConfig | None = None,
    *,
    force: bool = False,
) -> str:
    """Generate a complete Family Trust .docx from *data*.

    Returns the output path as a string.
    """
    cfg = config or load_config()
    fmt = DocxFormatter()
    gen = _TrustDocGen(data, fmt, cfg)
    gen.build(force=force)

    # Embed metadata in document properties
    props = fmt.doc.core_properties
    props.author = cfg.firm.name
    props.comments = f"Generated by trust-generator v{__version__}"
    props.category = "Family Trust"

    path_str = str(output_path)
    fmt.save(path_str)
    log.info("Trust document saved to %s", path_str)
    return path_str


class _TrustDocGen:
    """Internal builder — holds references to data, formatter, and config."""

    def __init__(self, data: TrustData, fmt: DocxFormatter, cfg: AppConfig) -> None:
        self.d = data
        self.f = fmt
        self.cfg = cfg

    # Convenience aliases
    @property
    def is_individual(self) -> bool:
        return self.d.trust_type == TrustType.INDIVIDUAL

    @property
    def grantor_name(self) -> str:
        return self.d.grantor_name

    @property
    def party_a(self) -> str:
        return self.d.party_a_name

    @property
    def party_b(self) -> str:
        return self.d.party_b_name

    @property
    def label_a(self) -> str:
        return self.d.party_a_label

    @property
    def label_b(self) -> str:
        return self.d.party_b_label

    @property
    def trust_name(self) -> str:
        return self.d.trust_name

    @property
    def trust_date(self) -> str:
        return self.d.trust_date

    @property
    def state(self) -> str:
        return self.d.state

    @property
    def county(self) -> str:
        return self.d.county

    @property
    def trustee_names(self) -> str:
        return self.d.trustee_names

    @cached_property
    def _p(self) -> dict[str, str]:
        """Pronoun/phrasing map for trust-type-dependent language."""
        if self.is_individual:
            return {
                "subject": "I",
                "subject_lc": "I",
                "object": "me",
                "possessive": "my",
                "possessive_cap": "My",
                "reflexive": "myself",
                "subject_have": "I have",
                "subject_may": "I may",
                "subject_request": "I request",
                "subject_intend": "I intend",
                "subject_create": "I create",
                "trustee_ref": "the Trustee",
                "trustee_ref_cap": "The Trustee",
                "grantor_ref": "the Grantor",
                "grantor_ref_plural": "the Grantor",
                "grantor_ref_cap": "the Grantor",
                "children_possessive": "my children",
            }
        return {
            "subject": "We",
            "subject_lc": "we",
            "object": "us",
            "possessive": "our",
            "possessive_cap": "Our",
            "reflexive": "ourselves",
            "subject_have": "We have",
            "subject_may": "Either Grantor may",
            "subject_request": "We request",
            "subject_intend": "We intend",
            "subject_create": "We create",
            "trustee_ref": "our Trustee",
            "trustee_ref_cap": "Our Trustee",
            "grantor_ref": "the Grantors",
            "grantor_ref_plural": "the Grantors",
            "grantor_ref_cap": "the Grantors",
            "children_possessive": "our children",
        }

    def _pre_generation_check(self) -> None:
        """Block generation if critical fields are missing."""
        critical = {
            "trust_name": self.trust_name,
            "trust_date": self.trust_date,
            "state": self.state,
            "county": self.county,
            "trustee_names": self.trustee_names,
            "ssn_owner_name": self.d.ssn_owner_name,
        }
        if self.is_individual:
            critical["grantor_name"] = self.grantor_name
        else:
            critical["party_a_name"] = self.party_a
            critical["party_b_name"] = self.party_b

        missing = [k for k, v in critical.items() if not v or v == "[MISSING]"]
        if missing:
            raise ValueError(
                f"Cannot generate: missing critical fields: {', '.join(missing)}. "
                f"Run validation first or provide the required data."
            )

    # --- Build sequence (matches original exactly) ---
    def build(self, *, force: bool = False) -> None:
        if not force:
            self._pre_generation_check()
        else:
            log.warning("Pre-generation safety check SKIPPED (force=True)")
        self._title_page()
        self.f.pb()
        self._article_1()
        self.f.pb()
        self._article_2()
        self.f.pb()
        self._article_3()
        self.f.pb()
        self._article_4()
        self.f.pb()
        self._article_5()
        self.f.pb()
        self._article_6()
        self.f.pb()
        self._article_7()
        self._article_8()
        self.f.pb()
        self._article_9()
        self.f.pb()
        self._article_10()
        self.f.pb()
        self._article_11()
        self.f.pb()
        self._article_12()
        self.f.pb()
        self._signatures()
        self.f.pb()
        self._schedules()

    # --- Title page ---
    def _title_page(self) -> None:
        self.f.blank(4)
        self.f.centered("THE", size=16, bold=True)
        self.f.centered(self.trust_name.upper(), size=18, bold=True)
        self.f.centered(f"Dated: {self.trust_date}", size=12)
        self.f.blank(6)
        firm = self.cfg.firm
        self.f.centered("Prepared by:")
        self.f.centered(firm.name, bold=True)
        self.f.centered(firm.address_line1)
        self.f.centered(firm.address_line2)
        self.f.centered(firm.phone)

    # --- Article 1: Establishing Our Trust ---
    def _article_1(self) -> None:
        if self.is_individual:
            self.f.h1("Article 1: Establishing My Trust")
            self.f.body(
                f"The date of this Trust is {self.trust_date}. The parties are "
                f"{self.grantor_name} (the \u201cGrantor\u201d) and "
                f"{self.trustee_names} (the \u201cTrustee\u201d). I have transferred "
                f"certain assets to the Trustee to be held in trust subject to "
                f"this instrument."
            )
            self.f.body(
                f"I intend to create a valid trust under the laws of {self.state}."
            )
        else:
            self.f.h1("Article 1: Establishing Our Trust")
            self.f.body(
                f"The date of this Trust is {self.trust_date}. The parties are "
                f"{self.party_a} and {self.party_b} (the \u201cGrantors\u201d) and "
                f"{self.trustee_names} (our \u201cTrustee(s)\u201d). We have transferred "
                f"certain assets to our Trustee(s) to be held in trust subject to "
                f"this instrument."
            )
            self.f.body(
                f"We intend to create a valid trust under the laws of {self.state}."
            )

        # 1.1 Family
        self.f.h2("1.1 Family")
        if self.is_individual:
            self.f.body(f"{self.grantor_name} is the \u201cGrantor.\u201d")
        else:
            self.f.body(
                f"{self.party_a} is \u201c{self.label_a}\u201d and {self.party_b} is "
                f"\u201c{self.label_b}.\u201d Both are \u201cwe,\u201d \u201cus,\u201d "
                f"\u201cour,\u201d or \u201cGrantors.\u201d"
            )
        children = self.d.children
        if children:
            self.f.body(f"{self._p['subject_have']} {len(children)} children:")
            for c in children:
                dob = f", born {c.dob}" if c.dob else ""
                self.f.indent(f"{c.name}{dob}")
            self.f.body(
                f"All references to \u201c{self._p['possessive']} children\u201d "
                f"mean these children. \u201c{self._p['possessive_cap']} "
                f"descendants\u201d means {self._p['possessive']} children and "
                f"their descendants."
            )
        else:
            self.f.highlight("[LIST CHILDREN HERE]")

        other = self.d.other_beneficiaries
        if other:
            self.f.body(f"{self._p['subject_have']} also provided for:")
            for b in other:
                rel = f" ({b.relationship})" if b.relationship else ""
                self.f.indent(f"{b.name}{rel}")

        # 1.2 Name of Trust
        self.f.h2("1.2 Name of Trust")
        self.f.body(
            f"This Trust shall be known as the {self.trust_name}. For transfers, "
            f"identify as: \u201c{self.trustee_names}, Trustee(s) of the "
            f"{self.trust_name}, dated {self.trust_date}, and any amendments "
            f"thereto.\u201d"
        )

        # 1.3 Certificate of Trust
        self.f.h2("1.3 Certificate of Trust and Third Party Reliance")
        self.f.body(
            f"{self._p['trustee_ref_cap']} may use a certification of trust "
            f"instead of this instrument. Third parties may rely upon it and are "
            f"not required to inquire into the Trust\u2019s terms or see to the "
            f"application of funds received by {self._p['trustee_ref']}."
        )

        # 1.4 Transferring Property
        self.f.h2(f"1.4 Transferring Property to {self._p['possessive_cap']} Trust")
        self.f.body(
            f"By executing this instrument, {self._p['subject_lc']} transfer the "
            f"property described in the attached schedules. At the time of "
            f"drafting, those assets include:"
        )
        for i, a in enumerate(self.d.asset_summary(), 1):
            self.f.indent(f"{i}. {a}")
        self.f.body(
            f"This instrument also considers additional assets "
            f"{self._p['subject_lc']} may obtain before this instrument becomes "
            f"irrevocable."
        )
        self.f.body(
            f"{self._p['trustee_ref_cap']} accepts and agrees to hold "
            f"transferred property as Trust property, to administer for "
            f"{self._p['possessive']} benefit and {self._p['possessive']} "
            f"beneficiaries\u2019 benefit."
        )

        if self.is_individual:
            self.f.body("All property transferred is the Grantor\u2019s property.")
        elif (
            self.d.elections.property_classification == PropertyClassification.COMMUNAL
        ):
            self.f.body("All property transferred is communal property.")
        else:
            self.f.body("Separate property is defined in Schedules C and D.")

        # 1.5 Intentions
        self.f.h2(f"1.5 Intentions of {self._p['grantor_ref']}")
        self.f.body(
            f"{self._p['subject_create']} this revocable living trust for "
            f"{self._p['possessive']} benefit while living, and for "
            f"{self._p['possessive']} beneficiaries after "
            f"{self._p['possessive']} death."
        )
        intent = self.d.text_blocks.statement_of_intent
        if intent:
            self.f.manual_review("Statement of Intent (from questionnaire)", intent)
        else:
            self.f.manual_review("Statement of Intent - Attorney to draft")

        # 1.6 Personal message (conditional)
        msg = self.d.text_blocks.personal_message
        if msg:
            self.f.h2(f"1.6 Message to {self._p['possessive_cap']} Beneficiaries")
            self.f.manual_review("Personal Message (from questionnaire)", msg)

        # 1.7 Grantor Trust Status
        self.f.h2("1.7 Grantor Trust Status")
        self.f.body(
            f"{self._p['subject_intend']} to qualify as a Grantor Trust under "
            f"IRC Sections 671-677. The Tax ID will be "
            f"{self.d.ssn_owner_name}\u2019s Social Security number."
        )

        # 1.8 Powers Reserved
        if self.is_individual:
            self.f.h2("1.8 Powers Reserved by Me as Grantor")
            self.f.body(
                "I may amend, restate, or revoke this instrument in writing. "
                "I may add or remove property at any time. I retain control of "
                "income and principal distributions. "
                "Undistributed income is added to principal."
            )
        else:
            self.f.h2("1.8 Powers Reserved by Us as Grantors")
            self.f.body(
                "Either of us may act for the Trust without the other\u2019s "
                "consent. We may jointly amend, restate, or revoke this instrument "
                "in writing. Either may add property; jointly we may remove "
                "property. We retain control of income and principal distributions. "
                "Undistributed income is added to principal."
            )

    # --- Article 2: Trustee Succession ---
    def _article_2(self) -> None:
        self.f.h1("Article 2: Trustee Succession")

        self.f.h2("2.1 Resignation")
        if self.is_individual:
            self.f.body(
                "A Trustee may resign by written notice to me, or if I am "
                "incapacitated or deceased, to beneficiaries and co-trustees."
            )
        else:
            self.f.body(
                "A Trustee may resign by written notice to either of us, or if "
                "both incapacitated or deceased, to beneficiaries and co-trustees."
            )

        self.f.h2("2.2 General Succession")
        if self.is_individual:
            self.f.body("If I cease to act as Trustee, succession is:")
        else:
            self.f.body(
                "If either of us ceases to act as Trustee, the surviving spouse "
                "continues as sole Trustee. If both are unable, succession is:"
            )
        for s in self.d.successor_trustees:
            rel = f" ({s.relationship})" if s.relationship else ""
            self.f.indent(f"{s.order}: {s.name}{rel}")
        if not self.d.successor_trustees:
            self.f.highlight("[LIST SUCCESSOR TRUSTEES]")

        self.f.h2("2.3 Contingent Succession")
        if self.is_individual:
            self.f.body(
                "If no designated Trustee can serve: I may appoint one; "
                "if I am unable, a majority of beneficiaries may appoint or "
                "petition the court."
            )
        else:
            self.f.body(
                "If no designated Trustee can serve: we may jointly appoint one; "
                "if only one of us survives, that spouse may appoint; if neither "
                "survives, a majority of beneficiaries may appoint or petition the "
                "court."
            )

        self.f.h2("2.4 Removal")
        if self.is_individual:
            self.f.body(
                "I may remove any Trustee. If I am incapacitated, a majority "
                "of my children may remove. After my death, a majority of "
                "Income Beneficiaries may remove."
            )
        else:
            self.f.body(
                "We may jointly remove any Trustee. During one\u2019s incapacity, "
                "the other may remove. If both incapacitated, a majority of our "
                "children may remove. After both deaths, a majority of Income "
                "Beneficiaries may remove."
            )

        self.f.h2("2.5 Incapacity of a Trustee")
        self.f.body(
            "A written declaration of incapacity by a co-Trustee or designated "
            "successor, supported by a physician\u2019s written opinion, "
            "terminates the trusteeship. An objecting Trustee has five days to "
            "object and must sign medical releases."
        )

        self.f.h2("2.6 Rights of Successor Trustees")
        self.f.body(
            "Successor Trustees have all rights and obligations of the initial "
            "Trustee. No successor need examine prior Trustee\u2019s records."
        )

    # --- Article 3: Administration During Our Lives / My Life ---
    def _article_3(self) -> None:
        if self.is_individual:
            self._article_3_individual()
        else:
            self._article_3_joint()

    def _article_3_individual(self) -> None:
        self.f.h1("Article 3: Administration During My Life")

        self.f.h2("3.1 Right to Amend or Revoke")
        self.f.body(
            "I may revoke or amend this Trust in whole or part by written "
            "instrument signed by me."
        )

        self.f.h2("3.2 Reserved")
        self.f.body("This section is intentionally reserved.")

        self.f.h2("3.3 Distributions During My Life")
        self.f.body(
            "While I am alive, I may use or distribute Trust property as if "
            "owned outside the Trust."
        )

        self.f.h2("3.4 Administration During Incapacity")
        self.f.body(
            "If I am incapacitated, the Trustee shall distribute for: "
            "(a) my benefit; (b) others for my benefit; (c) authorized "
            "agents; (d) my dependents."
        )

        self.f.h2("3.5 Determination of Incapacity")
        self.f.body(
            "Incapacity is established by two licensed physicians, court "
            "declaration, or unexplained absence exceeding 30 days. Capacity "
            "is restored by a physician\u2019s written opinion."
        )

    def _article_3_joint(self) -> None:
        self.f.h1("Article 3: Administration During Our Lives")

        self.f.h2("3.1 Right to Amend or Revoke")
        self.f.body(
            "While both alive, we may revoke or amend in whole or part by "
            "written agreement signed by both of us."
        )

        self.f.h2("3.2 Surviving Spouse\u2019s Amendment Rights")
        match self.d.elections.surviving_amendment:
            case SurvivingAmendment.FULL:
                self.f.body(
                    "The surviving spouse has full power to amend or revoke the "
                    "entire Trust."
                )
            case SurvivingAmendment.LIMITED:
                self.f.body(
                    "The surviving spouse may amend only the Survivor\u2019s "
                    "Trust and distributions for predeceased children."
                )
            case SurvivingAmendment.IRREVOCABLE:
                self.f.body("Upon the first death, this Trust becomes irrevocable.")

        self.f.h2("3.3 Distributions During Our Lives")
        self.f.body(
            "While both alive, we may use or distribute Trust property as if "
            "owned outside the Trust."
        )

        self.f.h2("3.4 Administration During Incapacity")
        self.f.body(
            "If one of us is incapacitated, our Trustee shall distribute for: "
            "(a) the incapacitated Grantor; (b) others for the Grantor\u2019s "
            "benefit; (c) authorized agents; (d) the other Grantor\u2019s HEMS; "
            "(e) dependents. Equal consideration shall be given to both "
            "Grantors\u2019 needs."
        )

        self.f.h2("3.5 Determination of Incapacity")
        self.f.body(
            "Incapacity is established by two licensed physicians, court "
            "declaration, or unexplained absence exceeding 30 days. Capacity "
            "is restored by a physician\u2019s written opinion."
        )

    # --- Article 4: Administration Upon Death ---
    def _article_4(self) -> None:
        if self.is_individual:
            self._article_4_individual()
        else:
            self._article_4_joint()

    def _article_4_individual(self) -> None:
        self.f.h1("Article 4: Administration Upon Death")

        self.f.h2("4.1 Trust Becomes Irrevocable")
        self.f.body(
            "Upon my death, this Trust becomes irrevocable. A separate "
            "Tax ID may be needed."
        )

        self.f.h2("4.2 Administrative Trust")
        self.f.body(
            "The Trustee shall administer the Trust property per this instrument."
        )

        self.f.h2("4.3 Payment of Expenses and Taxes")
        self.f.body(
            "The Trustee shall pay: (a) funeral and memorial expenses; "
            "(b) enforceable claims; (c) administration expenses; "
            "(d) court-ordered allowances; (e) all taxes including death taxes; "
            "(f) any tax-beneficial payments."
        )

        self.f.h2("4.4 Distribution of Tangible Personal Property")
        recip = (
            "my children"
            if self.d.elections.tangible_distribution
            == TangibleDistribution.EQUAL_CHILDREN
            else "my named beneficiaries"
        )
        self.f.body(
            f"The Trustee shall distribute tangible personal property to "
            f"{recip} in substantially equal shares. If unable to agree within "
            f"six months, the Trustee decides."
        )
        for b in self.d.specific_bequests:
            instr = f". {b.instructions}" if b.instructions else "."
            self.f.indent(
                f"I direct that {b.item} be distributed to {b.recipient}{instr}"
            )

        self.f.h2("4.5 Tax Elections")
        self.f.body("The Trustee may make necessary tax elections.")

        if self.d.elections.probate_coordination:
            self.f.h2("4.6 Coordination with Personal Representative")
            self.f.body(
                "The Trustee may rely on the Personal Representative\u2019s "
                "requests, accept property from probate, and distribute to the "
                "probate estate when beneficial."
            )

    def _article_4_joint(self) -> None:
        self.f.h1("Article 4: Administration Upon Death of a Grantor")

        self.f.h2("4.1 Surviving and Deceased Grantor\u2019s Property")
        self.f.body(
            "After the first death, the survivor\u2019s interest is the "
            "\u201cSurvivor\u2019s Trust\u201d (Article 5). The deceased\u2019s "
            "interest is the \u201cDeceased Grantor\u2019s Trust Property.\u201d"
        )

        self.f.h2("4.2 Administrative Trust")
        self.f.body(
            "The Trust becomes irrevocable as to the deceased\u2019s property. "
            "A separate Tax ID may be needed."
        )

        self.f.h2("4.3 Payment of Expenses and Taxes")
        self.f.body(
            "Our Trustee shall pay: (a) funeral and memorial expenses; "
            "(b) enforceable claims; (c) administration expenses; "
            "(d) court-ordered allowances; (e) all taxes including death taxes; "
            "(f) any tax-beneficial payments."
        )

        self.f.h2("4.4 Distribution of Tangible Personal Property")
        recip = (
            "our children"
            if self.d.elections.tangible_distribution
            == TangibleDistribution.EQUAL_CHILDREN
            else "our named beneficiaries"
        )
        self.f.body(
            f"Our Trustee shall distribute tangible personal property to "
            f"{recip} in substantially equal shares. If unable to agree within "
            f"six months, the Trustee decides."
        )
        for b in self.d.specific_bequests:
            instr = f". {b.instructions}" if b.instructions else "."
            self.f.indent(
                f"We direct that {b.item} be distributed to {b.recipient}{instr}"
            )

        self.f.h2("4.5 Tax Elections and Portability")
        self.f.body(
            "Our Trustee may make necessary tax elections. If the deceased\u2019s "
            "exclusion is not fully used, our Trustee is nominated as executor "
            "for portability under IRC Section 2010(c)(5)(A)."
        )

        # Fixed: this was always True in the original due to str(True) bug
        if self.d.elections.probate_coordination:
            self.f.h2("4.6 Coordination with Personal Representative")
            self.f.body(
                "Our Trustee may rely on the Personal Representative\u2019s "
                "requests, accept property from probate, and distribute to the "
                "probate estate when beneficial."
            )

    # --- Article 5: The Survivor's Trust / Incapacity Provisions ---
    def _article_5(self) -> None:
        if self.is_individual:
            self._article_5_individual()
        else:
            self._article_5_joint()

    def _article_5_individual(self) -> None:
        self.f.h1("Article 5: Incapacity Provisions")
        self.f.body(
            "This article provides for the administration of the Trust "
            "during my incapacity."
        )

        self.f.h2("5.1 Trustee During Incapacity")
        self.f.body(
            "If I am incapacitated, the successor Trustee designated in "
            "Article 2 shall serve. The successor Trustee shall administer "
            "Trust property for my benefit per Section 3.4."
        )

        self.f.h2("5.2 Standard of Care")
        self.f.body(
            "The Trustee shall maintain my accustomed standard of living "
            "and may distribute income and principal as needed for my "
            "health, education, maintenance, and support."
        )

        self.f.h2("5.3 Restoration of Capacity")
        self.f.body(
            "Upon restoration of capacity per Section 3.5, I resume full "
            "control of the Trust as Grantor and Trustee."
        )

        self.f.h2("5.4 Coordination with Power of Attorney")
        self.f.body(
            "The Trustee shall coordinate with any agent acting under my "
            "power of attorney to avoid duplication of effort."
        )

        self.f.h2("5.5 Power of Appointment")
        match self.d.elections.power_of_appointment:
            case PowerOfAppointment.GENERAL:
                self.f.body(
                    "I reserve the power to appoint all or any portion of "
                    "the Trust property at death among any persons or "
                    "entities, including creditors of my estate."
                )
            case PowerOfAppointment.LIMITED:
                self.f.body("I reserve the power to appoint among my descendants only.")
            case PowerOfAppointment.NONE:
                self.f.body("No power of appointment. Property passes per Article 6.")

        self.f.h2("5.6 After My Death")
        self.f.body(
            "Upon my death, this Trust becomes irrevocable. Administered "
            "per Article 4, then the balance passes per Article 6."
        )

    def _article_5_joint(self) -> None:
        self.f.h1("Article 5: The Survivor\u2019s Trust")
        self.f.body(
            "Our Trustee allocates the deceased\u2019s remaining property to "
            "the Survivor\u2019s Trust."
        )

        self.f.h2("5.1 Trustee")
        self.f.body(
            "The surviving Grantor may serve as sole Trustee and may remove or "
            "replace the Trustee at any time."
        )

        self.f.h2("5.2 Right to Amend")
        self.f.body(
            "Subject to Section 3.2, the surviving Grantor may amend, restate, "
            "or revoke the Survivor\u2019s Trust in writing."
        )

        self.f.h2("5.3 Income and Principal")
        self.f.body(
            "All net income distributed quarter-annually to the surviving "
            "Grantor. Principal as the surviving Grantor directs for any reason."
        )

        self.f.h2("5.4 Incapacity")
        self.f.body("During incapacity, administered per Section 3.4.")

        self.f.h2("5.5 General Power of Appointment")
        match self.d.elections.power_of_appointment:
            case PowerOfAppointment.GENERAL:
                self.f.body(
                    "The surviving Grantor may appoint all or any portion at "
                    "death among any persons or entities, including creditors "
                    "of the estate."
                )
            case PowerOfAppointment.LIMITED:
                self.f.body(
                    "The surviving Grantor may appoint among our descendants only."
                )
            case PowerOfAppointment.NONE:
                self.f.body("No power of appointment. Property passes per Article 6.")

        self.f.h2("5.6 After the Surviving Grantor\u2019s Death")
        self.f.body(
            "The Survivor\u2019s Trust becomes irrevocable. Administered per "
            "Article 4, then the unappointed balance passes per Article 6."
        )

    # --- Article 6: Distribution to Beneficiaries ---
    def _article_6(self) -> None:
        self.f.h1("Article 6: Distribution to Beneficiaries")

        self.f.h2("6.1 Division of Remaining Property")
        self.f.body(
            f"{self._p['trustee_ref_cap']} divides remaining property as follows:"
        )
        shares = self.d.beneficiary_shares
        if shares:
            self.f.add_table(
                headers=["Name", "Relationship", "Share", "Conditions"],
                rows=[
                    [s.name, s.relationship, f"{s.share}%", s.conditions]
                    for s in shares
                ],
            )
        else:
            self.f.highlight("[COMPLETE BENEFICIARY TABLE]")

        self.f.h2("6.2 Standard Distribution Terms")
        stxt = (
            "health, education, maintenance, or support"
            if self.d.elections.distribution_standard == DistributionStandard.HEMS
            else "any purpose"
        )
        self.f.body(
            f"{self._p['trustee_ref_cap']} shall distribute income and principal "
            f"as determined necessary for each beneficiary\u2019s {stxt}. "
            f"Undistributed income added to principal."
        )
        self.f.body(
            f"{self._p['subject_request']} {self._p['trustee_ref']} be liberal "
            f"in making distributions, considering the beneficiary\u2019s other "
            f"known resources. Principal may be exhausted."
        )
        self.f.body(self._withdrawal_text())

        self.f.h2("6.3 If a Beneficiary Is Deceased")
        match self.d.elections.beneficiary_death:
            case BeneficiaryDeath.PER_STIRPES_BENEFICIARY:
                self.f.body(
                    f"The deceased beneficiary\u2019s share passes per stirpes "
                    f"to their descendants, then to {self._p['possessive']} "
                    f"descendants, then per Article 7."
                )
            case BeneficiaryDeath.PER_STIRPES_GRANTORS:
                self.f.body(
                    f"The share passes per stirpes to "
                    f"{self._p['possessive']} descendants, then per Article 7."
                )
            case BeneficiaryDeath.REDISTRIBUTE:
                self.f.body(
                    "The share is redistributed equally among surviving named "
                    "beneficiaries."
                )

        # Custom terms
        custom = self.d.text_blocks.custom_distribution_terms
        custom_b = self.d.text_blocks.custom_beneficiary_terms
        combined = "\n".join(filter(None, [custom, custom_b]))
        if combined.strip():
            self.f.h2("6.4 Specific Terms by Beneficiary")
            self.f.manual_review("Custom terms from questionnaire", combined)

    # --- Article 7: Remote Contingent Distribution ---
    def _article_7(self) -> None:
        self.f.h1("Article 7: Remote Contingent Distribution")
        match self.d.elections.remote_contingent:
            case RemoteContingent.INTESTACY:
                self.f.body(
                    f"If no one is qualified to receive distribution, property "
                    f"passes per {self.state} intestacy laws."
                )
            case RemoteContingent.CHARITY:
                charity = (
                    self.d.elections.remote_contingent_charity or "[NAMED CHARITY]"
                )
                self.f.body(f"If no one is qualified, property passes to {charity}.")

    # --- Article 8: Underage and Incapacitated Beneficiaries ---
    def _article_8(self) -> None:
        self.f.h1("Article 8: Underage and Incapacitated Beneficiaries")
        self.f.body(
            f"For beneficiaries under 18 or incapacitated, "
            f"{self._p['trustee_ref']} may distribute directly, to a guardian, "
            f"as UTMA custodian, or to an agent. Alternatively, property may be "
            f"retained in a separate trust for HEMS distributions. Upon reaching "
            f"18 or restoration of capacity, the beneficiary may withdraw all "
            f"accumulated income and principal."
        )

    # --- Article 9: Retirement Plans and Life Insurance ---
    def _article_9(self) -> None:
        self.f.h1("Article 9: Retirement Plans and Life Insurance")

        self.f.h2("9.1 Retirement Plans")
        self.f.body(
            f"{self._p['trustee_ref_cap']} may determine manner and timing of "
            f"retirement plan payments consistent with IRC Section 401(a)(9). "
            f"{self._p['trustee_ref_cap']} may not change plan beneficiaries."
        )
        match self.d.elections.retirement_strategy:
            case RetirementStrategy.TRUST:
                self.f.manual_review(
                    "Retirement Plan Trust Provisions",
                    "Client elected Trust-controlled retirement. Draft "
                    "conduit/see-through provisions and review SECURE Act "
                    "compliance.",
                )
            case RetirementStrategy.MIX:
                self.f.manual_review(
                    "Mixed Retirement Strategy",
                    "Review Section 4 asset table for per-account designations.",
                )
            case RetirementStrategy.POD:
                pass  # POD: no special trust provisions needed

        self.f.h2("9.2 Life Insurance")
        if self.is_individual:
            self.f.body(
                "During my life, I reserve all rights over insurance "
                "policies. After my death, the Trustee collects proceeds payable to "
                "the Trust. Proceeds must never become part of my probate estate."
            )
        else:
            self.f.body(
                "During our lives, each reserves all rights over insurance "
                "policies. After death, our Trustee collects proceeds payable to "
                "the Trust. Proceeds must never become part of our probate estate."
            )

    # --- Article 10: Trust Administration ---
    def _article_10(self) -> None:
        self.f.h1("Article 10: Trust Administration")

        self.f.h2("10.1 Distributions")
        self.f.body(
            f"{self._p['trustee_ref_cap']} may make cash, in-kind, or mixed "
            f"distributions in any proportion without regard to tax attributes "
            f"or beneficiary consent."
        )

        self.f.h2("10.2 No Court Proceedings; No Bond")
        self.f.body(
            f"{self._p['trustee_ref_cap']} shall administer with efficiency and "
            f"freedom from judicial intervention. No bond is required."
        )
        if (
            self.d.elections.dispute_resolution
            == DisputeResolution.MEDIATION_ARBITRATION
        ):
            self.f.body(
                "Disputes should be resolved by mediation, then arbitration "
                "per the Uniform Arbitration Act."
            )

        self.f.h2("10.3 Trustee Compensation")
        match self.d.elections.trustee_compensation:
            case TrusteeCompensation.REASONABLE:
                self.f.body(
                    "Individual Trustees receive fair and reasonable "
                    "compensation. Corporate fiduciaries per their fee "
                    "schedule. All may be reimbursed."
                )
            case TrusteeCompensation.NONE:
                self.f.body(
                    "Family Trustees serve without compensation. Corporate "
                    "fiduciaries per their fee schedule. All may be reimbursed."
                )

        self.f.h2("10.4 Accounting")
        self.f.body(
            "After the first death, annual accounting to Income Beneficiaries "
            "unless waived. Objections within 60 days. Records available at "
            "reasonable times."
        )

        self.f.h2("10.5 Liability Limitations")
        self.f.body(
            "No Trustee liability unless bad faith shown by clear and "
            "convincing evidence."
        )

        self.f.h2("10.6 Merge, Sever, or Terminate Trusts")
        if self.is_individual:
            self.f.body(
                "The Trustee may merge, sever, or terminate trusts when "
                "economical. Terminated trust property distributed to: me if "
                "living; mandatory income beneficiaries; then "
                "discretionary income beneficiaries."
            )
        else:
            self.f.body(
                "Our Trustee may merge, sever, or terminate trusts when "
                "economical. Terminated trust property distributed to: us if "
                "living; surviving Grantor; mandatory income beneficiaries; then "
                "discretionary income beneficiaries."
            )

    # --- Article 11: Trustee's Powers ---
    def _article_11(self) -> None:
        self.f.h1("Article 11: Trustee\u2019s Powers")
        citation = self.cfg.jurisdiction.trust_code_citation
        if self.is_individual:
            self.f.body(
                f"The Trustee has all powers granted by this Trust and {self.state} "
                f"law, including the {citation}, incorporated herein. Powers "
                f"include: invest, bank, conduct business, sell/transfer, contract, "
                f"manage real estate, acquire residences, retain property, borrow, "
                f"hold in nominee form, insure, settle claims, execute documents."
            )

            self.f.h2("11.1 Limitations")
            self.f.body(
                "An Interested Trustee is limited to HEMS distributions per IRC "
                "Sections 2041 and 2514. When prohibited from acting, an "
                "Independent Special Trustee may be appointed. No Trustee may "
                "discharge their own legal obligations. These limitations do not "
                "apply while I serve as Trustee."
            )
        else:
            self.f.body(
                f"Our Trustee has all powers granted by this Trust and {self.state} "
                f"law, including the {citation}, incorporated herein. Powers "
                f"include: invest, bank, conduct business, sell/transfer, contract, "
                f"manage real estate, acquire residences, retain property, borrow, "
                f"hold in nominee form, insure, settle claims, execute documents."
            )

            self.f.h2("11.1 Limitations")
            self.f.body(
                "An Interested Trustee is limited to HEMS distributions per IRC "
                "Sections 2041 and 2514. When prohibited from acting, an "
                "Independent Special Trustee may be appointed. No Trustee may "
                "discharge their own legal obligations. These limitations do not "
                "apply while either of us serves as Trustee of the Survivor\u2019s "
                "Trust."
            )

    # --- Article 12: General Provisions ---
    def _article_12(self) -> None:
        self.f.h1("Article 12: General Provisions")

        self.f.h2("12.1 Maximum Term")
        if self.is_individual:
            self.f.body(
                "Each trust terminates 21 years after the death of the last "
                "descendant of my grandparents living at the time of my death."
            )
        else:
            self.f.body(
                "Each trust terminates 21 years after the death of the last "
                "descendant of our grandparents living at the time of the first of "
                "us to die."
            )

        # Fixed: these are now proper booleans that can actually be False
        if self.d.elections.spendthrift:
            self.f.h2("12.2 Spendthrift Provision")
            self.f.body(
                "All trusts are spendthrift trusts. No beneficiary may assign, "
                "anticipate, or encumber any interest. Neither income nor "
                "principal is subject to creditors or involuntary transfer."
            )

        if self.d.elections.no_contest:
            self.f.h2("12.3 Contest Provision")
            if self.is_individual:
                self.f.body(
                    "Any person who contests this Trust forfeits their share and "
                    "is deemed to have predeceased me."
                )
            else:
                self.f.body(
                    "Any person who contests this Trust forfeits their share and "
                    "is deemed to have predeceased the last of us."
                )

        self.f.h2("12.4 Survivorship Presumption")
        if self.is_individual:
            self.f.body(
                "A beneficiary dying within 30 days of the Grantor is deemed "
                "to have predeceased the Grantor."
            )
        else:
            self.f.body(
                "If we die simultaneously, each is deemed to have predeceased the "
                "other. A beneficiary dying within 30 days of a Grantor is deemed "
                "to have predeceased the Grantor."
            )

        self.f.h2("12.5 Definitions")
        for term, defn in [
            (
                "Adopted Persons",
                "Legally adopted before 18 have same rights as natural children.",
            ),
            (
                "Descendants",
                "Children, grandchildren, etc. Not nieces or nephews.",
            ),
            (
                "Education",
                "An ascertainable standard: schooling, college, vocational, "
                "tuition, room, board, fees.",
            ),
            ("Grantor", "Same as Settlor or Trustor."),
            ("Incapacity", "As defined in Section 3.5."),
            (
                "Income Beneficiary",
                "Beneficiary entitled to net income distributions.",
            ),
            (
                "Independent Trustee",
                "Not related or subordinate per IRC Section 672(c).",
            ),
            (
                "Per Stirpes",
                "Divided among children and deceased children\u2019s "
                "descendants equally.",
            ),
        ]:
            self.f.definition(term, defn)

        self.f.h2("12.6 Rules of Construction")
        self.f.body(
            f"Executed in counterparts. Governed by {self.state} law. Headings "
            f"for convenience. Notices in writing. Invalid provisions do not "
            f"affect others. No antilapse statutes apply."
        )

    # --- Signatures ---
    def _signatures(self) -> None:
        self.f.h1("Execution")
        self.f.body(f"Executed on {self.trust_date}. Effective when signed.")
        self.f.blank(3)
        if self.is_individual:
            self.f.body("________________________________________")
            self.f.body(f"{self.d.grantor_name}, Grantor and Trustee")
        else:
            self.f.body("________________________________________")
            self.f.body(f"{self.party_a}, Grantor and Trustee")
            self.f.blank(2)
            self.f.body("________________________________________")
            self.f.body(f"{self.party_b}, Grantor and Trustee")
        self.f.blank(2)
        self.f.body(f"STATE OF {self.state.upper()} )")
        self.f.body(") ss.")
        self.f.body(f"COUNTY OF {self.county.upper()} )")
        self.f.blank()
        if self.is_individual:
            self.f.body(
                f"Acknowledged before me on {self.trust_date}, by "
                f"{self.d.grantor_name}, as Grantor and Trustee."
            )
        else:
            self.f.body(
                f"Acknowledged before me on {self.trust_date}, by {self.party_a}, "
                f"as Grantor and Trustee, and {self.party_b}, as Grantor and Trustee."
            )
        self.f.blank(2)
        self.f.body("[Seal]")
        self.f.blank()
        self.f.body("________________________________________")
        self.f.body("Notary Public")
        self.f.body("My commission expires: _______________")

    # --- Schedules ---
    def _schedules(self) -> None:
        if self.is_individual:
            self.f.h1("Schedule A: Grantor\u2019s Property")
        else:
            self.f.h1("Schedule A: Communal Property")
        self.f.body("Transferred to this Trust:")
        self.f.blank()
        self.f.body("Ten Dollars Cash")
        if self.is_individual:
            self.f.manual_review("Additional property to be transferred")
        else:
            self.f.manual_review("Additional communal property")

        self.f.pb()
        self.f.h1("Schedule B: Memorandum of Distribution [OPTIONAL]")
        bequests = self.d.specific_bequests
        if bequests:
            for b in bequests:
                instr = f" ({b.instructions})" if b.instructions else ""
                self.f.indent(f"{b.item} \u2192 {b.recipient}{instr}")
        else:
            self.f.manual_review("Specific bequests if applicable")

        if (
            not self.is_individual
            and self.d.elections.property_classification
            == PropertyClassification.SEPARATE
        ):
            self.f.pb()
            self.f.h1(f"Schedule C: {self.label_a}\u2019s Separate Property")
            self.f.manual_review(f"{self.label_a}\u2019s separate property")
            self.f.pb()
            self.f.h1(f"Schedule D: {self.label_b}\u2019s Separate Property")
            self.f.manual_review(f"{self.label_b}\u2019s separate property")

    # --- Helpers ---
    def _withdrawal_text(self) -> str:
        steps = self.d.withdrawal_schedule
        if not steps:
            return (
                "At intervals to be determined, the beneficiary may withdraw "
                "from the trust share per a staggered schedule. "
                "[SPECIFY SCHEDULE]"
            )
        parts: list[str] = []
        for i, s in enumerate(steps):
            pct = s.percentage or "[XX]"
            timing = s.timing or "[X years after funding]"
            if i == 0:
                parts.append(
                    f"{pct}% of accumulated trust income and principal, {timing}"
                )
            else:
                parts.append(
                    f"increased by {pct}% of accumulated trust income and "
                    f"principal not already subject to withdrawal, {timing}"
                )
        text = (
            "At the intervals below, the beneficiary may withdraw amounts "
            "not exceeding:\n\n"
        )
        for i, p in enumerate(parts):
            text += f"    ({chr(97 + i)}) {p};\n\n"
        text += (
            "These rights are cumulative. A beneficiary exercises this right "
            f"by written notice to {self._p['trustee_ref']}. This right may not be subject "
            "to creditor claims or legal process, and may not be alienated or "
            "encumbered."
        )
        return text
